AirAjencyy/AirAjencyy/Models/AirPlane.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AirAjencyy.Models
{
	public class AirPlane
	{
		public int Id { get; set; }
		[DisplayName("نام هواپیما")]
		[Required(ErrorMessage = "نام هواپیما را وارد کنید")]
		public string airPlaneModel { get; set; }
		[DisplayName("تصویر هواپیما")]
		public string ImageUrl { get; set; }
	}
}

AirAjencyy/AirAjencyy/Areas/Admin/Controllers/PrimaryInformation/AirPlanesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AirAjencyy.Models;

namespace AirAjencyy.Areas.Admin.Controllers.PrimaryInformation
{
    public class AirPlanesController : Controller
    {
        private AirAjencyyContext db = new AirAjencyyContext();

        // GET: Admin/AirPlanes
        public async Task<ActionResult> Index(string name)
        {
			if(name !=null && name != "")
			{
				return View(await db.AirPlanes.Where(s=>s.airPlaneModel.Contains(name)).ToListAsync());

			}


			return View(await db.AirPlanes.ToListAsync());
        }

 

        // GET: Admin/AirPlanes/Create
        public ActionResult Create()
        {
            return View();
        }

    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,airPlaneModel,ImageUrl")] AirPlane airPlane, HttpPostedFileBase Main_Image)
        {
            if (ModelState.IsValid)
            {
				if (Main_Image != null)
				{



					if (!(Main_Image.ContentType == "image/jpeg" || Main_Image.ContentType == "image/png" || Main_Image.ContentType == "image/bmp"))
					{
						TempData["ErrorAirPlane"] = "نوع تصویر غیر قابل قبول است";
						return RedirectToAction(nameof(Create));
					}

					var name = Guid.NewGuid().ToString().Replace('-', '0') + "." + Main_Image.FileName.Split('.')[1];
					var imageUrl = "/Upload/Plane/" + name;
					string path = Server.MapPath(imageUrl);
					Main_Image.SaveAs(path);
					airPlane.ImageUrl = name;
				}
				db.AirPlanes.Add(airPlane);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(airPlane);
        }

        // GET: Admin/AirPlanes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AirPlane airPlane = await db.AirPlanes.FindAsync(id);
            if (airPlane == null)
            {
                return HttpNotFound();
            }
            return View(airPlane);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,airPlaneModel,ImageUrl")] AirPlane airPlane , HttpPostedFileBase Main_Image)
        {
            if (ModelState.IsValid)
            {
				var item = db.AirPlanes.Where(s => s.Id == airPlane.Id).FirstOrDefault();

				if (Main_Image != null)
				{
					if(item.ImageUrl != null)
					{
						System.IO.File.Delete(Server.MapPath(String.Concat("~/Upload/Plane/", item.ImageUrl)));

					}



					if (!(Main_Image.ContentType == "image/jpeg" || Main_Image.ContentType == "image/png" || Main_Image.ContentType == "image/bmp"))
					{
						TempData["ErrorAirPlane"] = "نوع تصویر غیر قابل قبول است";
						return RedirectToAction(nameof(Create));
					}

					var name = Guid.NewGuid().ToString().Replace('-', '0') + "." + Main_Image.FileName.Split('.')[1];
					var imageUrl = "/Upload/Plane/" + name;
					string path = Server.MapPath(imageUrl);
					Main_Image.SaveAs(path);
					item.ImageUrl = name;
				}

				item.airPlaneModel = airPlane.airPlaneModel;
				

		
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(airPlane);
        }


        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AirPlane airPlane = await db.AirPlanes.FindAsync(id);
            if (airPlane == null)
            {
                return HttpNotFound();
            }
            return View(airPlane);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            AirPlane airPlane = await db.AirPlanes.FindAsync(id);
			var haspic =await db.AirPlanes.Where(s => s.Id == id).FirstOrDefaultAsync();
			if(haspic.ImageUrl != null)
			{
				System.IO.File.Delete(Server.MapPath(String.Concat("~/Upload/Plane/",haspic.ImageUrl)));
			}

            db.AirPlanes.Remove(airPlane);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AirAjencyy/AirAjencyy/Areas/Admin/Views/AirPlanes/Create.cshtml
@model AirAjencyy.Models.AirPlane

@{
	ViewBag.Title = "Create";
	Layout = "~/Areas/Admin/Views/Shared/_Master.cshtml";
}



@using ((Html.BeginForm("Create",
                        "AirPlanes",
                        FormMethod.Post, new { enctype = "multipart/form-data" })))
{
	@Html.AntiForgeryToken()

	<div class="row">
		<div class="col-xs-12">
			<div class="box">

				<div class="text-center text-blue" style="border-style:solid;">
					<h2>ثبت هواپیما</h2>
				</div>

				<div class="form-horizontal">

					<hr />
					@Html.ValidationSummary(true, "", new { @class = "text-danger" })
					<div class="form-group">
						@Html.LabelFor(model => model.airPlaneModel, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.airPlaneModel, new { htmlAttributes = new { @class = "form-control", @style = "width:50%" } })
							@Html.ValidationMessageFor(model => model.airPlaneModel, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group" style="margin-right:100px;">
						<input style="width:712px;margin-right:50px" name="Main_Image" type="file" class="form-control" id="Main_Image_Upload" onchange="setImage()">
						<br />
						<img alt="بدون تصویر" id="Main_Image_Show" style="width:150px;height:150px;margin-right:50px" src="" />
					</div>

					<div class="form-group" style="margin-left:90%;">
						<div class="col-md-offset-2 col-md-10">
							<input type="submit" value="ثبت" class="btn btn-success" style="margin-bottom:5px;" />
						</div>
						<p class="text-danger" style="margin-right:20px;">
							@TempData["ErrorAirPlane"]
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
}


<div>
	<a class="btn btn-warning" href="/Admin/AirPlanes/Index"> بازگشت</a>
</div>
<script>

	function setImage() {

		var myURL = window.URL || window.webkitURL;
		var fileURL = myURL.createObjectURL(Main_Image_Upload.files[0]);
		Main_Image_Show.src = fileURL;
	}
</script>

AirAjencyy/AirAjencyy/Areas/Admin/Views/AirPlanes/Delete.cshtml
@model AirAjencyy.Models.AirPlane

@{
	ViewBag.Title = "Delete";
	Layout = "~/Areas/Admin/Views/Shared/_Master.cshtml";
}


<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-body table-responsive no-padding">

				<div class="text-center text-danger" style="border-style:solid;">
					<h2>آیا مطمعن به ادامه عملیات هستید؟ </h2>

				</div>
				<br />
				<hr />


				@using (Html.BeginForm())
				{
					@Html.AntiForgeryToken()


					<div class="form-actions no-color" style="margin-top:20px">
						<input type="submit" value="حذف" class="btn btn-danger" style="margin-bottom:5px;margin-right:5px;" /> |
						<a class="btn btn-warning" href="/Admin/AirPlanes/Index" style="margin-bottom:5px;"> انصراف</a>
					</div>
				}
			</div>
			</div>
</div>
</div>

AirAjencyy/AirAjencyy/Areas/Admin/Views/AirPlanes/Details.cshtml
@model AirAjencyy.Models.AirPlane

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Master.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AirPlane</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.airPlaneModel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.airPlaneModel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AirAjencyy/AirAjencyy/Areas/Admin/Views/AirPlanes/Edit.cshtml
@model AirAjencyy.Models.AirPlane

@{
	ViewBag.Title = "Edit";
	Layout = "~/Areas/Admin/Views/Shared/_Master.cshtml";
}




@using ((Html.BeginForm("Edit",
						"AirPlanes",
						FormMethod.Post, new { enctype = "multipart/form-data" })))
{
	@Html.AntiForgeryToken()
	<div class="row">
		<div class="col-xs-12">
			<div class="box">

				<div class="text-center text-blue" style="border-style:solid;">
					<h2>ثبت هواپیما</h2>
				</div>

				<div class="form-horizontal">

					<hr />
					@Html.ValidationSummary(true, "", new { @class = "text-danger" })
					@Html.HiddenFor(model => model.Id)

					<div class="form-group" style="margin-left:100px;">
						@Html.LabelFor(model => model.airPlaneModel, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.airPlaneModel, new { htmlAttributes = new { @class = "form-control",@style="width:50%" } })
							@Html.ValidationMessageFor(model => model.airPlaneModel, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group" style="margin-left:100px;">
						@Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
						<input style="width:50%;margin-right:50px" name="Main_Image" type="file" class="form-control" id="Main_Image_Upload" onchange="setImage()">
						<br />
						<img alt="بدون تصویر" id="Main_Image_Show" style="width:150px;height:150px;margin-right:50px" src="~/Upload/Plane/@Model.ImageUrl" />
					</div>

					<div class="form-group" style="margin-left:90%;">
						<div class="col-md-offset-2 col-md-10">
							<input type="submit" value="ثبت" class="btn btn-success" style="margin-bottom:5px;" />
						</div>
						<p class="text-danger" style="margin-right:20px;">
							@TempData["ErrorAirPlane"]
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
}

<script>

	function setImage() {

		var myURL = window.URL || window.webkitURL;
		var fileURL = myURL.createObjectURL(Main_Image_Upload.files[0]);
		Main_Image_Show.src = fileURL;
	}
</script>
<div>
	<a class="btn btn-warning" href="/Admin/AirPlanes/Index"> بازگشت</a>
</div>

AirAjencyy/AirAjencyy/Areas/Admin/Views/AirPlanes/Index.cshtml
@model IEnumerable<AirAjencyy.Models.AirPlane>

@{
	ViewBag.Title = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_Master.cshtml";
}

<div class="text-center" style="border-style:solid;">
	<h2 style="font-size:medium">مدیریت  نوع هواپیما</h2>
</div>
<br />
<p>



<p>

	<a class="btn btn-success" href="/Admin/AirPlanes/Create">ثبت جدید</a>

</p>
@using ((Html.BeginForm("Index",
						"AirPlanes",
						FormMethod.Post, new { enctype = "multipart/form-data" })))
{
	<input class="form-control" name="name" style="width:40%" placeholder="بر اساس مدل هواپیما جستجو کنید " />
	<button type="submit" class="btn btn-primary" style="margin-top:10px">جستجو</button>
}
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover text-center">
					<tr>
						<th>
							@Html.DisplayNameFor(model => model.airPlaneModel)
						</th>
						<th>
							@Html.DisplayNameFor(model => model.ImageUrl)
						</th>
						<th>
							عملیات
						</th>
					</tr>

					@foreach (var item in Model)
					{
						<tr>
							<td>
								@Html.DisplayFor(modelItem => item.airPlaneModel)
							</td>

							@if (item.ImageUrl != null)
							{
								<td>
									<img style="width:60px;height:50px;" src="~/Upload/Plane/@item.ImageUrl" />
								</td>
							}
							@if (item.ImageUrl == null)
							{
								<td>
									بدون عکس
								</td>
							}

							<td>
								<a class="btn btn-primary" href="/Admin/AirPlanes/Edit/@item.Id"> ویرایش</a> |

								<a class="btn btn-danger" href="/Admin/AirPlanes/Delete/@item.Id"> حذف</a>
							</td>
						</tr>
					}

				</table>
			</div>
		</div>
	</div>
</div>