AirAjencyy/AirAjencyy/Models/Factors.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AirAjencyy.Models
{
	public class Factors
	{
		public int Id { get; set; }
		public string CustomerName { get; set; }
		public string Mobile { get; set; }
		public string Address { get; set; }
		public DateTime CreateDate { get; set; }
		public int PlaneTicketID { get; set; }
		public PlaneTicket PlaneTicket { get; set; }
	}
}

AirAjencyy/AirAjencyy/Areas/Admin/Controllers/FactorsController.cs
using AirAjencyy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AirAjencyy.Areas.Admin.Controllers
{
    public class FactorsController : Controller
    {
		// GET: Admin/Factors
		private AirAjencyyContext db = new AirAjencyyContext();

		public ActionResult Index(string FromDate,string ToDate)
        {
			object listFactors = new object();
			if (FromDate!=null && ToDate != null && FromDate !="" && ToDate !="")
			{
				DateTime date1 = Utility.DateChanger.ToGeorgianDateTime(FromDate);
				DateTime date2 = Utility.DateChanger.ToGeorgianDateTime(ToDate);


				 listFactors = db.Factors.Where(s=>s.CreateDate >= date1  && s.CreateDate < date2).ToList();
				return View(listFactors);

			}


			listFactors = db.Factors.ToList();
			

            return View(listFactors);
        }
    }
}

AirAjencyy/AirAjencyy/Areas/Admin/Views/Factors/Index.cshtml
@model IEnumerable<AirAjencyy.Models.Factors>

@{
	ViewBag.Title = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_Master.cshtml";
	AirAjencyy.Models.AirAjencyyContext db = new AirAjencyy.Models.AirAjencyyContext();
}

<div class="text-center" style="border-style:solid;">
	<h2 style="font-size:medium">گزارش و مشاهده فاکتورها</h2>
</div>
<br />
<p>
	<div class="row">
		<div style="margin-right:20px;">
			@using ((Html.BeginForm("Index",
						"Factors",
						FormMethod.Post, new { enctype = "multipart/form-data" })))
			{
				<label>از تاریخ: </label>
				<input id="FromDate" name="FromDate" class="form-control" style="width:20%" />
				<label>تا تاریخ: </label>
				<input id="ToDate" name="ToDate" class="form-control" style="width:20%" />
				<input type="submit" value="جستجو" class="btn btn-primary" style="margin-bottom:5px;margin-top:10px;" />
			}
			</div>

		<div class="col-xs-12" style="margin-top:20px;">
			<div class="box">
				<div class="box-body table-responsive no-padding">
					<table class="table table-hover text-center">
						<tr>

							<th>
								نام و نام خانوادگی
							</th>
							<th>
								موبایل
							</th>
							<th>
								آدرس
							</th>
							<th>
								مبلغ خرید
							</th>

							<th>
								تاریخ ثبت
							</th>
						</tr>

						@foreach (var item in Model)
						{
							<tr>

								<td>
									@Html.DisplayFor(modelItem => item.CustomerName)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Mobile)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Address)
								</td>
								<td>
									@{
										var price = db.PlaneTickets.Where(s => s.Id == item.PlaneTicketID).FirstOrDefault();

									}
									@price.Price تومان

								</td>
								<td>
									@AirAjencyy.Utility.DateChanger.ToPersianDateString(item.CreateDate)

								</td>
								<td>
								</td>
							</tr>
						}

					</table>
				</div>
			</div>
		</div>
	</div>
	<link href="~/Areas/Css/jquery-ui.css" rel="stylesheet" />
	<link href="~/Areas/Css/jquery-ui-datetimepicker.min.css" rel="stylesheet" />
	<script src="~/Areas/scripts/jquery-1.10.2.min.js"></script>
	<script src="~/Areas/scripts/jquery-ui.js"></script>
	<script src="~/Areas/scripts/PersianDateTimePicker/jquery-ui-datetimepicker.min.js"></script>
	<script>
		$(document).ready(function () {
			$("#FromDate").datepicker();
			$("#ToDate").datepicker();

		});
	</script>